name: Docker Build

on:
  workflow_run:
    workflows: ["Test Suite"]
    types: [completed]
    branches: [ main ]

# Permissions pour GitHub Container Registry
permissions:
  contents: read
  packages: write

run-name: Docker Build - ${{ github.event.workflow_run.head_commit.message }}

jobs:
  # Check if tests succeeded
  check-tests-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Tests passed
        run: echo "Tests workflow completed successfully"

  # Build and push Docker images
  docker:
    runs-on: ubuntu-latest
    needs: [check-tests-success]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ghcr.io/${{ github.repository_owner }}/dishdash-backend
          ghcr.io/${{ github.repository_owner }}/dishdash-frontend
        tags: |
          type=ref,event=branch
          type=sha,prefix={{branch}}-

    - name: Build and push backend image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/dishdash-backend:latest
        labels: ${{ steps.meta.outputs.labels }}

    - name: Build and push frontend image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/dishdash-frontend:latest
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}